### ISSUE TITLE
PF

### ISSUE THREAD

**Issue by moniyama** [NiEl0503/SAP010-card-validation#1]
Parabéns @NiEl0503! 👏 
Projeto completo com as funcionalidades implantadas. 
Acredito que o mais importante é fazer a correção do teste unitário em que estava falhando.

OAs a serem reforçados no próximo projeto:
- UX/UI: usabilidade e prototipação (figma)
- Box model
- Uso de linter
- ES Modules

Pontos que podem ser melhorados:
- Planejamento
- Mensagens de commits
- Uso do atributo `alt` nas tag de img
- Printar a mensagem de validação abaixo do botão ou em outra região

**Comment by NiEl0503** [comment]
Obrigada @moniyama
